

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

--CREATE TABLE "REGISTRATIONS" ("ID" INTEGER NOT NULL IDENTITY, "CUSTOMER_ID" INTEGER, "EVENT_ID" INTEGER);
CREATE TABLE "CUSTOMERS" ("ID" INTEGER NOT NULL IDENTITY, "CUSTOMER_NAME" VARCHAR(255), "EMAIL" VARCHAR(255), "PASSWORD" VARCHAR(255));
CREATE TABLE "EVENTS" ("ID" INTEGER NOT NULL IDENTITY, "EVENT_CODE" VARCHAR(255), "TITLE" VARCHAR(255), "DESCRIPTION" VARCHAR(255), "EVENT_DATE" VARCHAR(255));

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- primary/unique
--ALTER TABLE "EVENTS" ADD CONSTRAINT "SQL120325130144010" PRIMARY KEY ("ID");
--ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "SQL120325130144011" PRIMARY KEY ("ID");
--ALTER TABLE "REGISTRATIONS" ADD CONSTRAINT "SQL120325130144013" PRIMARY KEY ("ID");
